# 1. Read a .csv from a URL with pandas
- Target website: https://www.football-data.co.uk/data.php

In [9]:
import pandas as pd

In [10]:
# reading 1 csv file from the website
df_premier21 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/E0.csv')

In [11]:
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [12]:
# rename columns
df_premier21.rename(columns={'FTHG':'home_goals','FTAG':'away_goals'},inplace=True)

In [6]:
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

# 2. Read .csv from multiple URL's with pandas
https://www.football-data.co.uk/mmz4281/2122/E0.csv
- Link: root+season+league

In [7]:
# link structure
"https://www.football-data.co.uk/mmz4281/"+"2122"+"/"+"E0"+".csv"

'https://www.football-data.co.uk/mmz4281/2122/E0.csv'

In [13]:
# creat a root variable
root = "https://www.football-data.co.uk/mmz4281/"

In [14]:
# create a list of leagues
leagues = ['E0','E1','E2','E3','EC']
frames = []

#looping through leagues, read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv(root + '2122' + '/' + league + '.csv', encoding = 'unicode_escape')
    frames.append(df)

In [15]:
# length of the frame
len(frames)

5

In [16]:
# show 1sr, 2nd and 3rd element
frames[0]

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [8]:
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,EC,21/08/2021,15:00,Aldershot,Chesterfield,0,2,A,0,0,...,1.93,0.50,1.98,1.83,2.03,1.83,2.05,1.90,1.97,1.80
1,EC,21/08/2021,15:00,Barnet,Notts County,0,5,A,0,0,...,2.06,0.75,1.88,1.93,1.90,1.95,2.00,1.95,1.90,1.88
2,EC,21/08/2021,15:00,Halifax,Maidenhead,1,2,A,1,0,...,1.94,-0.50,1.93,1.88,1.99,1.87,2.03,1.93,1.94,1.84
3,EC,21/08/2021,15:00,Kings Lynn,Southend,0,1,A,0,1,...,1.91,0.25,1.75,2.05,1.81,2.06,1.90,2.11,1.76,2.02
4,EC,21/08/2021,15:00,Solihull,Wrexham,2,2,D,1,2,...,1.85,0.00,2.05,1.75,1.93,1.92,2.05,1.98,1.92,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,EC,15/05/2022,15:00,Dover Athletic,Weymouth,1,2,A,0,1,...,2.50,0.25,1.88,1.93,1.87,1.98,1.90,1.98,1.85,1.93
502,EC,15/05/2022,15:00,Eastleigh,Grimsby,4,4,D,0,2,...,2.30,0.50,1.88,1.93,1.88,1.98,1.95,1.98,1.87,1.90
503,EC,15/05/2022,15:00,Maidenhead,Notts County,0,1,A,0,0,...,2.42,0.50,1.95,1.85,2.03,1.83,2.03,1.96,1.92,1.87
504,EC,15/05/2022,15:00,Southend,Torquay,1,1,D,0,1,...,2.01,-0.25,2.02,1.77,2.03,1.83,2.07,1.85,2.00,1.80
505,EC,15/05/2022,15:00,Stockport,Halifax,2,0,H,1,0,...,1.97,-0.75,1.80,2.00,1.79,2.08,1.93,2.08,1.84,1.95

# Multiple Seasons

In [17]:
for season in range(15,21):
    print(str(season)+str(season+1))

1516
1617
1718
1819
1920
2021

In [18]:
# create a list of leagues
leagues = ['E0','E2','E3']
frames = []

#looping through leagues, read multiple csv and append it into a list
for league in leagues:
    for season in range(15,21):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + league + '.csv')
        df.insert(1, 'season', season)
        frames.append(df)

In [19]:
# total frames (6 seasons x 3 leagues)
len(frames)

18

In [20]:
# show 1st, and last element(new season column was created)
frames[0]

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,1.79,26,-0.50,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,1.99,27,-1.50,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,1.96,26,-1.00,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,1.67,26,-0.50,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,2.01,26,-1.00,2.20,2.09,1.82,1.78,1.64,4.07,6.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,15,15/05/2016,Stoke,West Ham,2,1,H,0,1,...,2.27,30,0.25,2.11,2.03,1.87,1.83,3.05,4.00,2.26
376,E0,15,15/05/2016,Swansea,Man City,1,1,D,1,1,...,2.45,31,1.00,2.14,2.05,1.85,1.81,7.05,5.00,1.47
377,E0,15,15/05/2016,Watford,Sunderland,2,2,D,0,1,...,2.10,29,-0.50,2.06,2.01,1.91,1.85,1.64,4.52,5.27
378,E0,15,15/05/2016,West Brom,Liverpool,1,1,D,1,1,...,2.09,30,-0.25,2.10,2.05,1.86,1.81,2.61,3.75,2.70
379,E0,15,17/05/2016,Man United,Bournemouth,3,1,H,1,0,...,2.20,29,-0.75,1.88,1.84,2.08,2.02,1.50,4.60,7.03

In [21]:
frames[17]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,20,12/09/2020,15:00,Barrow,Stevenage,1,1,D,1,...,1.76,-0.25,1.95,1.90,1.93,1.98,1.98,1.99,1.91,1.92
1,E3,20,12/09/2020,15:00,Bolton,Forest Green,0,1,A,0,...,1.79,-0.25,2.02,1.83,2.04,1.87,2.09,1.90,2.00,1.83
2,E3,20,12/09/2020,15:00,Bradford,Colchester,0,0,D,0,...,1.65,-0.25,2.07,1.72,2.11,1.82,2.20,1.82,2.09,1.76
3,E3,20,12/09/2020,15:00,Cambridge,Carlisle,3,0,H,2,...,1.70,-0.25,1.98,1.88,2.02,1.88,2.04,1.90,1.99,1.84
4,E3,20,12/09/2020,15:00,Cheltenham,Morecambe,1,2,A,1,...,1.75,-0.50,1.83,2.02,1.87,2.04,1.88,2.09,1.83,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,20,08/05/2021,15:00,Port Vale,Mansfield,0,3,A,0,...,1.84,0.25,1.90,1.95,1.89,2.00,1.95,2.07,1.85,1.97
548,E3,20,08/05/2021,15:00,Scunthorpe,Stevenage,0,1,A,0,...,1.73,0.50,1.80,2.05,1.84,2.06,1.87,2.14,1.77,2.07
549,E3,20,08/05/2021,15:00,Southend,Newport County,1,1,D,1,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
550,E3,20,08/05/2021,15:00,Tranmere,Colchester,0,0,D,0,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
551,E3,20,08/05/2021,16:00,Salford,Leyton Orient,3,0,H,1,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86

In [22]:
frames[5]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,20,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,20,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,20,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,20,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,20,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,20,23/05/2021,16:00,Liverpool,Crystal Palace,2,0,H,1,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,20,23/05/2021,16:00,Man City,Everton,5,0,H,2,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,20,23/05/2021,16:00,Sheffield United,Burnley,1,0,H,1,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,20,23/05/2021,16:00,West Ham,Southampton,3,0,H,2,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,20,23/05/2021,16:00,Wolves,Man United,1,2,A,1,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88

# Organize All the Data in a Dictionary

In [27]:
# create a dictionary with original name of league as key
dict_countries = {
    'Spanish Ls Liga':'SP1',
    'Spanish Segunda Division':'SP2',
    'German Buneslinga':'D1',
    'English Premier League':'E0',
    'English League 1':'E2',
    'English League 1':'E3'
}

In [24]:
dict_countries['Spanish Ls Liga']

'SP1'

In [30]:
for league in dict_countries:
    print(dict_countries)
    print(dict_countries[league])

{'Spanish Ls Liga': 'SP1', 'Spanish Segunda Division': 'SP2', 'German Buneslinga': 'D1', 'English Premier League': 'E0', 'English League 1': 'E3'}
SP1
{'Spanish Ls Liga': 'SP1', 'Spanish Segunda Division': 'SP2', 'German Buneslinga': 'D1', 'English Premier League': 'E0', 'English League 1': 'E3'}
SP2
{'Spanish Ls Liga': 'SP1', 'Spanish Segunda Division': 'SP2', 'German Buneslinga': 'D1', 'English Premier League': 'E0', 'English League 1': 'E3'}
D1
{'Spanish Ls Liga': 'SP1', 'Spanish Segunda Division': 'SP2', 'German Buneslinga': 'D1', 'English Premier League': 'E0', 'English League 1': 'E3'}
E0
{'Spanish Ls Liga': 'SP1', 'Spanish Segunda Division': 'SP2', 'German Buneslinga': 'D1', 'English Premier League': 'E0', 'English League 1': 'E3'}
E3

In [33]:
dict_historical_data = {}

#looping t
# create a list of leagues
# leagues = ['E0','E2','E3']


#looping through leagues, read multiple csv and append it into a list
for league in dict_countries:
    frames = []
    for season in range(15,21):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + dict_countries[league] + '.csv')
        df.insert(1, 'season', season)
        frames.append(df)
    df_concat = pd.concat(frames)  
    dict_historical_data[league] = df_concat

In [35]:
# showing dataframe inside dict_historical_data
dict_historical_data.keys()

dict_keys(['Spanish Ls Liga', 'Spanish Segunda Division', 'German Buneslinga', 'English Premier League', 'English League 1'])

In [36]:
dict_historical_data.values()

dict_values([     Div  season        Date     HomeTeam    AwayTeam  FTHG  FTAG FTR  HTHG  \
0    SP1      15    21/08/15       Malaga     Sevilla     0     0   D     0
1    SP1      15    22/08/15   Ath Madrid  Las Palmas     1     0   H     1
2    SP1      15    22/08/15      Espanol      Getafe     1     0   H     1
3    SP1      15    22/08/15    La Coruna    Sociedad     0     0   D     0
4    SP1      15    22/08/15    Vallecano    Valencia     0     0   D     0
..   ...     ...         ...          ...         ...   ...   ...  ..   ...
375  SP1      20  22/05/2021      Osasuna    Sociedad     0     1   A     0
376  SP1      20  22/05/2021  Real Madrid  Villarreal     2     1   H     0
377  SP1      20  22/05/2021   Valladolid  Ath Madrid     1     2   A     1
378  SP1      20  23/05/2021      Granada      Getafe     0     0   D     0
379  SP1      20  23/05/2021      Sevilla      Alaves     1     0   H     0

     HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  \
0       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
1       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
2       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
3       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
4       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
..    ...  ...      ...   ...       ...       ...    ...    ...      ...
375     0  ...     2.34  1.00      2.07      1.86   2.06   1.87     2.07
376     1  ...     2.57 -1.00      2.01      1.92   2.00   1.93     2.02
377     0  ...     2.30  1.50      1.90      2.03   1.90   2.02     1.95
378     0  ...     1.80  0.25      1.73      2.08   1.77   2.18     1.84
379     0  ...     2.40 -1.50      1.97      1.96   1.93   1.99     2.13

     MaxCAHA  AvgCAHH  AvgCAHA
0        NaN      NaN      NaN
1        NaN      NaN      NaN
2        NaN      NaN      NaN
3        NaN      NaN      NaN
4        NaN      NaN      NaN
..       ...      ...      ...
375     1.96     1.98     1.88
376     2.02     1.95     1.92
377     2.06     1.90     1.97
378     2.23     1.77     2.12
379     2.03     1.99     1.88

[2280 rows x 127 columns],      Div  season        Date      HomeTeam    AwayTeam  FTHG  FTAG FTR  HTHG  \
0    SP2      15    22/08/15      Alcorcon    Mallorca     2     0   H   1.0
1    SP2      15    22/08/15       Cordoba  Valladolid     1     0   H   0.0
2    SP2      15    22/08/15        Huesca      Alaves     2     3   A   0.0
3    SP2      15    22/08/15    Llagostera     Osasuna     0     2   A   0.0
4    SP2      15    23/08/15       Almeria     Leganes     3     2   H   3.0
..   ...     ...         ...           ...         ...   ...   ...  ..   ...
457  SP2      20  30/05/2021      Mirandes    Sabadell     0     2   A   0.0
458  SP2      20  30/05/2021  Ponferradina    Mallorca     2     2   D   1.0
459  SP2      20  30/05/2021      Sp Gijon     Almeria     0     2   A   0.0
460  SP2      20  30/05/2021     Vallecano        Lugo     0     1   A   0.0
461  SP2      20  30/05/2021      Zaragoza     Leganes     0     5   A   0.0

     HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  \
0     0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
1     0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
2     1.0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
3     0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
4     0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
..    ...  ...      ...   ...       ...       ...    ...    ...      ...
457   0.0  ...     1.74  0.50      2.02      1.83   2.05   1.86     2.06
458   1.0  ...     1.83  0.25      2.00      1.85   2.02   1.89     2.04
459   0.0  ...     1.83 -0.75      1.80      2.05   1.84   2.08     1.89
460   1.0  ...     1.87 -1.00      1.95      1.90   1.97   1.93     2.02
461   3.0  ...     1.64  0.50      1.83      2.02   1.85   2.07     1.87

     MaxCAHA  AvgCAHH  AvgCAHA
0        NaN      NaN      NaN
1        NaN      NaN      NaN
2        NaN      NaN      NaN
3        NaN      NaN      NaN
4        NaN      NaN      NaN
..       ...      ...      ...
457     1.89     2.00     1.83
458     1.92     1.99     1.85
459     2.08     1.83     2.02
460     1.94     1.96     1.88
461     2.08     1.80     2.04

[2772 rows x 127 columns],     Div  season        Date       HomeTeam    AwayTeam  FTHG  FTAG FTR  HTHG  \
0    D1      15    14/08/15  Bayern Munich     Hamburg     5     0   H     1
1    D1      15    15/08/15       Augsburg      Hertha     0     1   A     0
2    D1      15    15/08/15      Darmstadt    Hannover     2     2   D     1
3    D1      15    15/08/15       Dortmund  M'gladbach     4     0   H     3
4    D1      15    15/08/15     Leverkusen  Hoffenheim     2     1   H     1
..   ..     ...         ...            ...         ...   ...   ...  ..   ...
301  D1      20  22/05/2021     Hoffenheim      Hertha     2     1   H     0
302  D1      20  22/05/2021      Stuttgart   Bielefeld     0     2   A     0
303  D1      20  22/05/2021   Union Berlin  RB Leipzig     2     1   H     0
304  D1      20  22/05/2021  Werder Bremen  M'gladbach     2     4   A     0
305  D1      20  22/05/2021      Wolfsburg       Mainz     2     3   A     0

     HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  \
0       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
1       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
2       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
3       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
4       1  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
..    ...  ...      ...   ...       ...       ...    ...    ...      ...
301     1  ...     2.96 -0.75      1.86      2.07   1.88   2.06     1.99
302     0  ...     2.50 -0.25      2.03      1.90   2.02   1.90     2.06
303     0  ...     2.34  0.50      1.97      1.96   1.97   1.95     1.98
304     1  ...     2.52  0.25      2.04      1.89   2.03   1.90     2.07
305     1  ...     2.97 -0.75      2.05      1.75   2.09   1.83     2.13

     MaxCAHA  AvgCAHH  AvgCAHA
0        NaN      NaN      NaN
1        NaN      NaN      NaN
2        NaN      NaN      NaN
3        NaN      NaN      NaN
4        NaN      NaN      NaN
..       ...      ...      ...
301     2.08     1.88     2.00
302     1.91     2.01     1.87
303     1.98     1.92     1.95
304     1.91     2.00     1.87
305     1.89     2.04     1.83

[1836 rows x 127 columns],     Div  season        Date          HomeTeam        AwayTeam  FTHG  FTAG FTR  \
0    E0      15  08/08/2015       Bournemouth     Aston Villa     0     1   A
1    E0      15  08/08/2015           Chelsea         Swansea     2     2   D
2    E0      15  08/08/2015           Everton         Watford     2     2   D
3    E0      15  08/08/2015         Leicester      Sunderland     4     2   H
4    E0      15  08/08/2015        Man United       Tottenham     1     0   H
..   ..     ...         ...               ...             ...   ...   ...  ..
375  E0      20  23/05/2021         Liverpool  Crystal Palace     2     0   H
376  E0      20  23/05/2021          Man City         Everton     5     0   H
377  E0      20  23/05/2021  Sheffield United         Burnley     1     0   H
378  E0      20  23/05/2021          West Ham     Southampton     3     0   H
379  E0      20  23/05/2021            Wolves      Man United     1     2   A

     HTHG  HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
0       0     0  ...      NaN   NaN       NaN       NaN    NaN    NaN
1       2     1  ...      NaN   NaN       NaN       NaN    NaN    NaN
2       0     1  ...      NaN   NaN       NaN       NaN    NaN    NaN
3       3     0  ...      NaN   NaN       NaN       NaN    NaN    NaN
4       1     0  ...      NaN   NaN       NaN       NaN    NaN    NaN
..    ...   ...  ...      ...   ...       ...       ...    ...    ...
375     1     0  ...     3.49 -2.25      1.86      2.04   1.88   2.03
376     2     0  ...     2.77 -1.75      2.01      1.89   1.99   1.89
377     1     0  ...     2.05  0.00      2.04      1.86   2.05   1.86
378     2     0  ...     2.14 -0.75      2.00      1.90   2.02   1.91
379     1     2  ...     1.62 -0.25      2.04      1.86   2.10   1.84

     MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
0        NaN      NaN      NaN      NaN
1        NaN      NaN      NaN      NaN
2        NaN      NaN      NaN      NaN
3        NaN      NaN      NaN      NaN
4        NaN      NaN      NaN      NaN
..       ...      ...      ...      ...
375     1.98     2.14     1.88     2.00
376     2.20     2.00     2.03     1.85
377     2.17     1.90     2.03     1.84
378     2.06     2.01     1.99     1.89
379     2.10     1.94     2.00     1.88

[2280 rows x 128 columns],     Div  season        Date       HomeTeam        AwayTeam  FTHG  FTAG FTR  \
0    E3      15    08/08/15     Accrington           Luton   1.0   1.0   D
1    E3      15    08/08/15  AFC Wimbledon        Plymouth   0.0   2.0   A
2    E3      15    08/08/15    Bristol Rvs     Northampton   0.0   1.0   A
3    E3      15    08/08/15      Cambridge  Newport County   3.0   0.0   H
4    E3      15    08/08/15         Exeter          Yeovil   3.0   2.0   H
..   ..     ...         ...            ...             ...   ...   ...  ..
547  E3      20  08/05/2021      Port Vale       Mansfield   0.0   3.0   A
548  E3      20  08/05/2021     Scunthorpe       Stevenage   0.0   1.0   A
549  E3      20  08/05/2021       Southend  Newport County   1.0   1.0   D
550  E3      20  08/05/2021       Tranmere      Colchester   0.0   0.0   D
551  E3      20  08/05/2021        Salford   Leyton Orient   3.0   0.0   H

     HTHG  HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
0     0.0   0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
1     0.0   1.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
2     0.0   0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
3     1.0   0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
4     2.0   0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
..    ...   ...  ...      ...   ...       ...       ...    ...    ...
547   0.0   2.0  ...     1.84  0.25      1.90      1.95   1.89   2.00
548   0.0   0.0  ...     1.73  0.50      1.80      2.05   1.84   2.06
549   1.0   0.0  ...     1.44  0.50      1.93      1.93   1.94   1.94
550   0.0   0.0  ...     1.59 -0.75      2.05      1.80   2.05   1.85
551   1.0   0.0  ...     1.87 -1.00      1.98      1.88   1.99   1.90

     MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
0        NaN      NaN      NaN      NaN
1        NaN      NaN      NaN      NaN
2        NaN      NaN      NaN      NaN
3        NaN      NaN      NaN      NaN
4        NaN      NaN      NaN      NaN
..       ...      ...      ...      ...
547     1.95     2.07     1.85     1.97
548     1.87     2.14     1.77     2.07
549     1.97     1.97     1.91     1.91
550     2.08     1.89     2.01     1.82
551     2.01     1.96     1.96     1.86

[3201 rows x 128 columns]])

In [37]:
dict_historical_data['English Premier League']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,20,23/05/2021,Liverpool,Crystal Palace,2,0,H,1,0,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,20,23/05/2021,Man City,Everton,5,0,H,2,0,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,20,23/05/2021,Sheffield United,Burnley,1,0,H,1,0,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,20,23/05/2021,West Ham,Southampton,3,0,H,2,0,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,20,23/05/2021,Wolves,Man United,1,2,A,1,2,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88