In [1]:
import pandas as pd

In [2]:
df_exams = pd.read_csv('StudentsPerformance.csv')

In [3]:
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Selecting one column

In [4]:
# way 1 -> This is the preferred way
df_exams['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: str

In [5]:
# check out the type of column
type(df_exams['gender'])

pandas.Series

In [7]:
# series : attributes and methods
df_exams['gender'].index

RangeIndex(start=0, stop=1000, step=1)

In [8]:
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: str

In [9]:

# way 2
# select a column with .
df_exams.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: str

In [12]:
# pitfalls
df_exams.math score

SyntaxError: invalid syntax (3045932672.py, line 2)

In [13]:
df_exams['math score']

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

# Selecting the Two columns
1. [] -> Series
2. [[]] -> DataFrame

In [14]:
# selecting 2 columns using [[]]
df_exams[['gender','math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [15]:
df_exams[['reading score','writing score']]

     reading score  writing score
0               72             74
1               90             88
2               95             93
3               57             44
4               78             75
..             ...            ...
995             99             95
996             55             55
997             71             65
998             78             77
999             86             86

[1000 rows x 2 columns]

In [16]:
type(df_exams[['reading score','writing score']])

pandas.DataFrame

In [17]:
# selecting the two or more columns
df_exams[['gender','math score','reading score','writing score']]

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

In [ ]:
# we can't select 2 or more columns with the '.'